FROM eclipse-temurin:21-jre
ENV MB_PLUGINS_DIR=/plugins
RUN mkdir -p  /app
ADD https://downloads.metabase.com/v0.58.8/metabase.jar /app/metabase.jar
ADD https://github.com/motherduckdb/metabase_duckdb_driver/releases/download/1.4.3.1/duckdb.metabase-driver.jar /
EXPOSE 3000
CMD ["java", "-jar", "/app/metabase.jar"]
